import { useAddDraft } from "@/hooks/notifications/useAddDraft";
import { useUsers } from "@/hooks/user/useUsers";
import React, { useState } from "react";
import {
  Alert,
  ScrollView,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const OPTIONS = [
  { label: "Todos los usuarios", value: "all" },
  { label: "Estudiantes", value: "students" },
  { label: "Instructores", value: "instructors" },
];

interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
}

interface Draft {
  id: string;
  title: string;
  content: string;
  recipients: User[];
}

export default function DraftScreen() {
  const useAddDraftMutation = useAddDraft();
  const usersQuery = useUsers();
  const [recipientQuery, setRecipientQuery] = useState("");
  const [draft, setDraft] = useState({
    title: "",
    content: "",
    recipients: [],
  });

  const handleChange = (key: keyof Draft, value: any) => {
    setDraft({ ...draft, [key]: value });
  };

  const saveDraftLocal = () => {
    if (!draft.title || !draft.content) {
      Alert.alert("Error", "Título y contenido obligatorios.");
      return;
    }

    useAddDraftMutation.mutate({
      id: "", // ID will be generated by Firestore
      title: draft.title,
      content: draft.content,
      recipients: draft.recipients,
    });

    setDraft({
      title: "",
      content: "",
      recipients: [],
    });
  };

  const filteredUsers = usersQuery.data?.filter((user) =>
    user.email.toLowerCase().includes(recipientQuery.toLowerCase())
  );

  return (
    <SafeAreaView className="flex-1 bg-gray-950">
      <ScrollView className="flex-1 p-5">
        <Text className="text-2xl font-bold text-white mb-3">
          Editor de Borradores
        </Text>

        <TextInput
          placeholder="Título"
          placeholderTextColor="#aaa"
          value={draft.title}
          onChangeText={(text) => handleChange("title", text)}
          className="bg-neutral-800 text-white p-3 rounded-xl mb-3"
        />

        <TextInput
          placeholder="Contenido"
          placeholderTextColor="#aaa"
          value={draft.content}
          onChangeText={(text) => handleChange("content", text)}
          multiline
          className="bg-neutral-800 text-white p-3 rounded-xl mb-3 min-h-[100px] text-top"
        />

        {/* Destinatarios seleccionados */}
        <View className="flex-row flex-wrap mb-3">
          {draft.recipients.map((r) => (
            <View key={r.id} className="bg-yellow-600 px-2 py-1 m-1 rounded-md">
              <Text className="text-white">{r.email}</Text>
            </View>
          ))}
        </View>

        {/* Botón Guardar */}
        <View className="flex-row justify-between mb-5">
          <TouchableOpacity
            onPress={saveDraftLocal}
            className="bg-secondary p-3 rounded-xl flex-1"
          >
            <Text className="text-white text-center font-semibold">
              Guardar Borrador
            </Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
